import type {
  ApiKey,
  Collection,
  DashboardData,
  Machine,
  SessionDetailData,
  SessionSummary,
  ShareGrant,
  TimelineGroup,
  Transfer,
} from './types';

export const demoSessions: SessionSummary[] = [
  {
    id: '0191cafe-1000-7000-8000-000000000001',
    title: 'Fix session parser branch recovery',
    summary: 'Traced a missing parent reference through the Codex normalizer and added a branch-safe mapping.',
    source: 'codex',
    sourceLabel: 'Codex',
    workspace: 'memoarhq/memoar',
    branch: 'fix/canonical-parents',
    machine: 'Atlas · MacBook Pro',
    model: 'gpt-5.5-codex',
    createdAt: '2026-08-17T14:42:00.000Z',
    updatedAt: '2026-08-17T15:31:00.000Z',
    turnCount: 34,
    tokenCount: 18420,
    durationMinutes: 49,
    redactionStatus: 'reviewed',
    tags: ['parser', 'canonical'],
    pinned: true,
  },
  {
    id: '0191cafe-1000-7000-8000-000000000002',
    title: 'Design redaction review gate',
    summary: 'Mapped the share-link flow so visibility cannot widen until every secret finding is reviewed.',
    source: 'claude-code',
    sourceLabel: 'Claude Code',
    workspace: 'memoarhq/memoar',
    branch: 'feat/sharing',
    machine: 'Atlas · MacBook Pro',
    model: 'claude-opus-4.1',
    createdAt: '2026-08-17T11:02:00.000Z',
    updatedAt: '2026-08-17T12:18:00.000Z',
    turnCount: 28,
    tokenCount: 23680,
    durationMinutes: 76,
    redactionStatus: 'findings',
    tags: ['sharing', 'privacy'],
  },
  {
    id: '0191cafe-1000-7000-8000-000000000003',
    title: 'Build hybrid search ranking smoke suite',
    summary: 'Added lexical fail-open cases and pinned reciprocal-rank fusion behavior against seeded sessions.',
    source: 'antigravity-cli',
    sourceLabel: 'Antigravity',
    workspace: 'memoarhq/memoar',
    branch: 'test/search-ranking',
    machine: 'Kepler · Linux workstation',
    model: 'gemini-3.0-pro',
    createdAt: '2026-08-17T08:44:00.000Z',
    updatedAt: '2026-08-17T09:22:00.000Z',
    turnCount: 19,
    tokenCount: 12760,
    durationMinutes: 38,
    redactionStatus: 'clear',
    tags: ['search', 'tests'],
  },
  {
    id: '0191cafe-1000-7000-8000-000000000004',
    title: 'Convert Claude history to Codex rollout',
    summary: 'Validated tool-call degradation and produced a conversion report with an injection fallback.',
    source: 'cursor',
    sourceLabel: 'Cursor',
    workspace: 'memoarhq/memoar',
    branch: 'feat/convert-codex',
    machine: 'Kepler · Linux workstation',
    model: 'composer-2',
    createdAt: '2026-08-16T18:04:00.000Z',
    updatedAt: '2026-08-16T19:11:00.000Z',
    turnCount: 41,
    tokenCount: 31290,
    durationMinutes: 67,
    redactionStatus: 'reviewed',
    tags: ['convert', 'codex'],
  },
  {
    id: '0191cafe-1000-7000-8000-000000000005',
    title: 'Investigate upload queue retry storm',
    summary: 'Found a missing jitter window in the offline queue and documented the idempotency boundary.',
    source: 'goose',
    sourceLabel: 'Goose',
    workspace: 'memoarhq/agent',
    branch: 'fix/upload-backoff',
    machine: 'Orion · Framework 13',
    model: 'claude-sonnet-4.0',
    createdAt: '2026-08-16T13:28:00.000Z',
    updatedAt: '2026-08-16T14:06:00.000Z',
    turnCount: 22,
    tokenCount: 10940,
    durationMinutes: 38,
    redactionStatus: 'clear',
    tags: ['agent', 'sync'],
  },
  {
    id: '0191cafe-1000-7000-8000-000000000006',
    title: 'Prototype pack freshness policy',
    summary: 'Compared strict and mixed evidence selection with stale citations kept explicit in output metadata.',
    source: 'codex',
    sourceLabel: 'Codex',
    workspace: 'memoarhq/memoar',
    branch: 'feat/pack',
    machine: 'Atlas · MacBook Pro',
    model: 'gpt-5.5-codex',
    createdAt: '2026-08-15T16:20:00.000Z',
    updatedAt: '2026-08-15T17:05:00.000Z',
    turnCount: 26,
    tokenCount: 15120,
    durationMinutes: 45,
    redactionStatus: 'clear',
    tags: ['memory', 'pack'],
    pinned: true,
  },
  {
    id: '0191cafe-1000-7000-8000-000000000007',
    title: 'Trace TypeORM tenant isolation query',
    summary: 'Audited the repository boundary and added a failing cross-tenant collection membership case.',
    source: 'claude-code',
    sourceLabel: 'Claude Code',
    workspace: 'memoarhq/server',
    branch: 'test/tenancy',
    machine: 'Atlas · MacBook Pro',
    model: 'claude-opus-4.1',
    createdAt: '2026-08-15T09:12:00.000Z',
    updatedAt: '2026-08-15T10:38:00.000Z',
    turnCount: 37,
    tokenCount: 28910,
    durationMinutes: 86,
    redactionStatus: 'findings',
    tags: ['server', 'security'],
  },
  {
    id: '0191cafe-1000-7000-8000-000000000008',
    title: 'Document native source discovery',
    summary: 'Consolidated verified storage paths for six coding agents with per-source health diagnostics.',
    source: 'antigravity-cli',
    sourceLabel: 'Antigravity',
    workspace: 'memoarhq/docs',
    branch: 'docs/source-table',
    machine: 'Kepler · Linux workstation',
    model: 'gemini-3.0-pro',
    createdAt: '2026-08-14T14:31:00.000Z',
    updatedAt: '2026-08-14T15:10:00.000Z',
    turnCount: 16,
    tokenCount: 8420,
    durationMinutes: 39,
    redactionStatus: 'clear',
    tags: ['docs', 'sources'],
  },
  {
    id: '0191cafe-1000-7000-8000-000000000009',
    title: 'Review MCP retrieval tool descriptions',
    summary: 'Reordered discovery from search to excerpt to pack and made full-session retrieval a last resort.',
    source: 'cursor',
    sourceLabel: 'Cursor',
    workspace: 'memoarhq/mcp',
    branch: 'docs/tool-budgeting',
    machine: 'Orion · Framework 13',
    model: 'composer-2',
    createdAt: '2026-08-13T17:48:00.000Z',
    updatedAt: '2026-08-13T18:17:00.000Z',
    turnCount: 14,
    tokenCount: 7140,
    durationMinutes: 29,
    redactionStatus: 'reviewed',
    tags: ['mcp', 'docs'],
  },
];

const timelineDates = ['2026-08-17', '2026-08-16', '2026-08-15', '2026-08-14', '2026-08-13'];

export const demoTimeline: TimelineGroup[] = timelineDates.map((date) => ({
  date,
  sessions: demoSessions.filter((session) => session.updatedAt.startsWith(date)),
}));

export const demoCollections: Collection[] = [
  {
    id: 'collection-1',
    name: 'Memoar launch',
    description: 'Architecture decisions and work that must land before the first full-system demo.',
    sessionCount: 18,
    updatedAt: '2026-08-17T15:31:00.000Z',
    color: '#d6ff78',
    members: [demoSessions[0]!.id, demoSessions[1]!.id, demoSessions[3]!.id],
  },
  {
    id: 'collection-2',
    name: 'Retrieval quality',
    description: 'Search ranking, pack budgeting, evidence freshness, and citation behavior.',
    sessionCount: 9,
    updatedAt: '2026-08-17T09:22:00.000Z',
    color: '#7dd3fc',
    members: [demoSessions[2]!.id, demoSessions[5]!.id],
  },
  {
    id: 'collection-3',
    name: 'Security review',
    description: 'Redaction, tenancy, secret handling, and visibility boundaries.',
    sessionCount: 7,
    updatedAt: '2026-08-15T10:38:00.000Z',
    color: '#f0a6ca',
    members: [demoSessions[1]!.id, demoSessions[6]!.id],
  },
  {
    id: 'collection-4',
    name: 'Source adapters',
    description: 'Native storage research, sync health, and parser format notes.',
    sessionCount: 24,
    updatedAt: '2026-08-14T15:10:00.000Z',
    color: '#c4b5fd',
    members: [demoSessions[4]!.id, demoSessions[7]!.id],
  },
];

export const demoGrants: ShareGrant[] = [
  {
    id: 'grant-1',
    sessionId: demoSessions[0]!.id,
    sessionTitle: demoSessions[0]!.title,
    permission: 'viewer',
    status: 'active',
    token: 'mshr_••••8R2H',
    createdAt: '2026-08-17T15:44:00.000Z',
    expiresAt: '2026-08-24T15:44:00.000Z',
    views: 4,
  },
  {
    id: 'grant-2',
    sessionId: demoSessions[5]!.id,
    sessionTitle: demoSessions[5]!.title,
    permission: 'importer',
    status: 'active',
    token: 'mshr_••••Q91A',
    createdAt: '2026-08-16T09:20:00.000Z',
    expiresAt: null,
    views: 12,
  },
];

export const demoTransfers: Transfer[] = [
  {
    id: 'transfer-1',
    sessionId: demoSessions[3]!.id,
    sessionTitle: demoSessions[3]!.title,
    senderEmail: 'avery@example.test',
    recipientEmail: 'you@example.test',
    status: 'pending',
    direction: 'incoming',
    createdAt: '2026-08-17T13:08:00.000Z',
  },
  {
    id: 'transfer-2',
    sessionId: demoSessions[7]!.id,
    sessionTitle: demoSessions[7]!.title,
    senderEmail: 'you@example.test',
    recipientEmail: 'sam@example.test',
    status: 'accepted',
    direction: 'outgoing',
    createdAt: '2026-08-14T16:42:00.000Z',
  },
];

export const demoMachines: Machine[] = [
  {
    id: 'machine-1',
    name: 'Atlas',
    platform: 'macOS 15.6 · arm64',
    status: 'online',
    lastSeenAt: '2026-08-17T16:12:00.000Z',
    agentVersion: '0.1.0',
    sources: [
      { id: 'claude-code', label: 'Claude Code', enabled: true, state: 'synced', sessionCount: 284, lastSyncAt: '2026-08-17T16:11:00.000Z' },
      { id: 'codex', label: 'Codex', enabled: true, state: 'syncing', sessionCount: 167, lastSyncAt: '2026-08-17T16:10:00.000Z' },
      { id: 'cursor', label: 'Cursor', enabled: true, state: 'attention', sessionCount: 91, lastSyncAt: '2026-08-17T13:44:00.000Z' },
    ],
  },
  {
    id: 'machine-2',
    name: 'Kepler',
    platform: 'Ubuntu 26.04 · x64',
    status: 'online',
    lastSeenAt: '2026-08-17T16:09:00.000Z',
    agentVersion: '0.1.0',
    sources: [
      { id: 'antigravity-cli', label: 'Antigravity', enabled: true, state: 'synced', sessionCount: 78, lastSyncAt: '2026-08-17T16:08:00.000Z' },
      { id: 'codex', label: 'Codex', enabled: true, state: 'synced', sessionCount: 46, lastSyncAt: '2026-08-17T16:08:00.000Z' },
    ],
  },
  {
    id: 'machine-3',
    name: 'Orion',
    platform: 'Fedora 43 · x64',
    status: 'offline',
    lastSeenAt: '2026-08-16T22:14:00.000Z',
    agentVersion: '0.0.9',
    sources: [
      { id: 'goose', label: 'Goose', enabled: true, state: 'synced', sessionCount: 51, lastSyncAt: '2026-08-16T22:13:00.000Z' },
      { id: 'cursor', label: 'Cursor', enabled: false, state: 'disabled', sessionCount: 0, lastSyncAt: null },
    ],
  },
];

export const demoApiKeys: ApiKey[] = [
  {
    id: 'key-1',
    name: 'Claude Code MCP',
    prefix: 'mmr_live_7K9F',
    scopes: ['sessions:read', 'collections:read', 'notes:write'],
    createdAt: '2026-08-12T10:00:00.000Z',
    lastUsedAt: '2026-08-17T16:04:00.000Z',
  },
  {
    id: 'key-2',
    name: 'Local automation',
    prefix: 'mmr_live_3P2D',
    scopes: ['sessions:read', 'pack:read'],
    createdAt: '2026-08-10T08:20:00.000Z',
    lastUsedAt: '2026-08-16T21:11:00.000Z',
  },
];

export const demoDashboard: DashboardData = {
  timeline: demoTimeline,
  collections: demoCollections,
  grants: demoGrants,
  transfers: demoTransfers,
  machines: demoMachines,
  apiKeys: demoApiKeys,
};

export function makeDemoDetail(session: SessionSummary): SessionDetailData {
  return {
    session,
    provenance: [
      {
        kind: 'native',
        sourceId: `${session.source}:${session.id.slice(-4)}`,
        capturedAt: session.updatedAt,
        parserVersion: '0.1.0',
      },
    ],
    tokenTotals: { input: 11320, output: 7100, cacheRead: 4890 },
    turns: [
      {
        id: 'turn-1',
        ordinal: 0,
        parentId: null,
        role: 'user',
        createdAt: session.createdAt,
        blocks: [
          {
            id: 'block-1',
            kind: 'text',
            text: 'The imported session loses its branch after a tool result. Find the normalization bug, preserve the native parent reference, and add a regression test.',
          },
        ],
      },
      {
        id: 'turn-2',
        ordinal: 1,
        parentId: 'turn-1',
        role: 'assistant',
        createdAt: '2026-08-17T14:44:00.000Z',
        model: session.model,
        tokens: { input: 2340, output: 1180 },
        blocks: [
          {
            id: 'block-2',
            kind: 'thinking',
            text: 'I need to compare the source parent identifier with the normalized turn map. The likely failure is that a tool result creates a synthetic turn before the parent lookup runs.',
          },
          {
            id: 'block-3',
            kind: 'tool_call',
            name: 'read_file',
            callId: 'call-1',
            data: { path: 'server/libs/parsers/src/codex/normalize.ts', line_start: 88, line_end: 146 },
          },
          {
            id: 'block-4',
            kind: 'tool_result',
            callId: 'call-1',
            status: 'success',
            text: '88  const nativeParent = event.parent_id\n89  const parentId = turnIds.get(event.id)\n90  return { ...turn, parentId }',
          },
          {
            id: 'block-5',
            kind: 'text',
            text: 'The lookup uses the current event id instead of `nativeParent`. That makes the first child appear valid, then detaches every branch after a tool result. I will correct the lookup and keep `null` for a true root.',
          },
        ],
      },
      {
        id: 'turn-3',
        ordinal: 2,
        parentId: 'turn-2',
        role: 'assistant',
        createdAt: '2026-08-17T15:02:00.000Z',
        model: session.model,
        tokens: { input: 1980, output: 1540 },
        blocks: [
          {
            id: 'block-6',
            kind: 'diff',
            path: 'server/libs/parsers/src/codex/normalize.ts',
            oldText: 'const parentId = turnIds.get(event.id) ?? null;',
            newText: 'const parentId = nativeParent ? turnIds.get(nativeParent) ?? null : null;',
          },
          {
            id: 'block-7',
            kind: 'tool_call',
            name: 'run_tests',
            callId: 'call-2',
            data: { command: 'npm test -- codex-normalize.spec.ts' },
          },
          {
            id: 'block-8',
            kind: 'tool_result',
            callId: 'call-2',
            status: 'success',
            text: 'PASS codex-normalize.spec.ts\n  ✓ preserves parent links across tool results\n  12 tests passed in 1.42s',
          },
        ],
      },
      {
        id: 'turn-4',
        ordinal: 3,
        parentId: 'turn-3',
        role: 'assistant',
        createdAt: session.updatedAt,
        model: session.model,
        tokens: { input: 620, output: 420 },
        blocks: [
          {
            id: 'block-9',
            kind: 'text',
            text: '## Result\n\nThe normalizer now resolves `parentId` from the native parent reference. The regression fixture covers a user turn, assistant tool call, tool result, and branched follow-up.\n\n- Parent links survive synthetic tool turns.\n- Root turns still normalize to `null`.\n- The fixture and parser suite pass.',
          },
        ],
      },
    ],
  };
}
