import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { ArchiveStore } from "../src/archive-store.js";
import { ARCHIVE_STORE } from "../src/tokens.js";
import { arr, startTestApi, str, type JsonBody, type TestApi } from "./helpers/http-app.js";

let api: TestApi;

/** An account that is not the one these tests sign in as. */
const FOREIGN_TENANT = "0191cafe-0000-7000-8000-0000000fa001";
const FOREIGN_MACHINE = "0191cafe-0000-7000-8000-0000000fa002";

beforeAll(async () => { api = await startTestApi(); }, 30_000);
afterAll(async () => { if (api) await api.close(); });

/** The agent's fallback name, which several unrelated laptops will report. */
const FALLBACK_NAME = "memoar-machine";

async function register(body: Record<string, unknown>): Promise<JsonBody> {
  const response = await api.request("POST", "/machines", { body });
  expect(response.status, JSON.stringify(response.body)).toBe(201);
  return response.body;
}

async function machineIds(): Promise<string[]> {
  const listed = await api.request("GET", "/machines");
  expect(listed.status).toBe(200);
  return arr(listed.body).map((machine) => str(machine, "id"));
}

/**
 * `POST /machines` created a row per call, and the agent called it on every
 * `login`. One dev account ended up with five machines for one laptop, four of
 * them byte-identical but for the generated uuid. Memory documents are unique
 * on (tenant, machine, path), so every surplus machine duplicated every
 * instruction file: 346 documents across 173 paths, each pair sharing a content
 * hash. A client-side fix alone leaves every other client free to do it again,
 * so the archive itself has to recognise a machine it already has.
 */
describe("registering a machine the account already has", () => {
  it("returns the machine this installation enrolled, rather than a second one", async () => {
    const installationId = "installation-same-laptop-0001";
    const first = await register({ name: FALLBACK_NAME, platform: "macos", installationId });
    const before = await machineIds();

    const again = await register({ name: FALLBACK_NAME, platform: "macos", installationId });

    expect(str(again, "id")).toBe(str(first, "id"));
    expect(await machineIds()).toEqual(before);
  });

  it("recognises the same installation across a platform the client spells differently", async () => {
    // The agent sends Rust's `std::env::consts::OS` and a Node client sends
    // `process.platform`, so one laptop reported "darwin" before an upgrade and
    // "macos" after. Identity is the installation id, and the platform is
    // normalised on the way in, so neither can split a machine in two.
    const installationId = "installation-upgraded-agent-01";
    const first = await register({ name: "franes-mac", platform: "darwin", installationId, agentVersion: "0.2.0" });
    expect(first.platform).toBe("macos");

    const again = await register({ name: "franes-mac", platform: "macos", installationId, agentVersion: "0.3.0" });

    expect(str(again, "id")).toBe(str(first, "id"));
    // What the installation reports now is what the machine list shows.
    expect(again.agentVersion).toBe("0.3.0");
    expect(again.platform).toBe("macos");
  });

  it("keeps two agents deliberately run on one host apart", async () => {
    // Same hostname, same platform, different config directories. Anything that
    // deduplicated on name and platform would fuse these, and because memory
    // documents are keyed on the machine, the two homes' CLAUDE.md files would
    // then overwrite each other instead of merely duplicating.
    const one = await register({ name: FALLBACK_NAME, platform: "macos", installationId: "installation-agent-alpha-1" });
    const two = await register({ name: FALLBACK_NAME, platform: "macos", installationId: "installation-agent-beta-01" });

    expect(str(two, "id")).not.toBe(str(one, "id"));
  });

  it("registers every time for a client that names no installation", async () => {
    // The archive will not infer an identity a client declined to state: with
    // nothing but a name and a platform to go on, guessing would merge machines
    // that are genuinely different.
    const one = await register({ name: FALLBACK_NAME, platform: "macos" });
    const two = await register({ name: FALLBACK_NAME, platform: "macos" });

    expect(str(two, "id")).not.toBe(str(one, "id"));
  });

  it("never resolves another account's installation", async () => {
    // Installation ids are generated by clients, so two accounts can hold the
    // same one — and resolving across the tenant boundary would hand the caller
    // somebody else's machine to file its memory files under.
    const installationId = "installation-shared-by-two-01";
    const store = api.app.get<ArchiveStore>(ARCHIVE_STORE);
    const other = { tenantId: FOREIGN_TENANT, userId: FOREIGN_TENANT, scopes: ["*"], authType: "dev" as const };
    await store.saveMachine(other, {
      id: FOREIGN_MACHINE, tenantId: FOREIGN_TENANT, name: FALLBACK_NAME,
      platform: "macos", agentVersion: null, sourceSettings: {}, lastSeenAt: null, installationId,
    });

    const mine = await register({ name: FALLBACK_NAME, platform: "macos", installationId });

    expect(str(mine, "id")).not.toBe(FOREIGN_MACHINE);
    expect(await store.findMachineByInstallation(other, installationId)).toMatchObject({ id: FOREIGN_MACHINE });
  });

  it("refuses an installation id short enough to have been hardcoded", async () => {
    // A client shipping a constant here would collapse an entire account onto
    // one machine, which loses documents rather than duplicating them.
    const response = await api.request("POST", "/machines", {
      body: { name: FALLBACK_NAME, platform: "macos", installationId: "agent" },
    });
    expect(response.status).toBe(400);
  });
});
